### ISSUE TITLE
Reference File

### ISSUE THREAD

**Issue by abhinavmittra** [cbouy/ProLIF#2]
I apologise for the clumsiness but I'm new to using Prolif and I have to use it to generate an interaction fingerprint.
Can you kindly explain the input parameters if possible?
I can't understand what is to be input as the reference file.

Thank You.

**Comment by cbouy** [comment]
Hi,
What I call the "reference" is typically a ligand that was co-cristallized with the protein you're interested in, or a docking pose of a ligand that is known to interact with your protein. This reference is used for 2 things here:
- Automatically identify protein residues that are close to your ligand. The list of residues will then be used for generating interaction fingerprints (IFP). You can provide your own list of residues to bypass this step.
- Calculate a similarity score (usually a Tanimoto score) between your reference and any other molecule in your virtual screening library. The Tanimoto score will be computed based on the IFPs of your reference and any molecule.

For example, if you're interested in [this protein](http://www.rcsb.org/3d-view/6MFD/1), the isobutyryl-CoA could be used as your reference. The resulting command would be something like 
```bash
prolif	--protein 6MFD_protein.mol2 \
	--reference 6MFD_isobutyryl-CoA.mol2 \
	--ligand 6MFD_docking-output/*.mol2
```
If you're only interested in generating an IFP and not in the similarity score, you can use the following python code to get an IFP:
```python
from prolif.ligand import Ligand
from prolif.protein import Protein
from prolif.fingerprint import Fingerprint

# create the fingerprint generator
fp = Fingerprint()
# load your protein
protein = Protein('my_protein.mol2', residueList=['C12', 'E29', 'K88'])
# load a ligand
molecule = Ligand('my_ligand.mol2')
# generate the IFP
fp.generateIFP(molecule, protein)
print(molecule.IFP)
```

If needed you can customize which type of interactions you want for your IFP, and also provide custom parameters to optimize the way these interactions are detected. This is done by calling `fp = Fingerprint(json_file='your_parameters.json', interactions=['HBdonor','HBacceptor'])`. The default JSON parameters file is [here](https://github.com/cbouy/ProLIF/blob/master/prolif/parameters.json).

Please keep in mind that this is a work in progress, so I haven't got the time to fully optimize the parameters or run extensive tests yet.

Don't hesitate if you have other questions.
Cédric

**Comment by abhinavmittra** [comment]
Thank you so much, I'm just interested in generating the IFP for now.
I tried running the code that you provided to me for a "1hyv.mol2" protein and "tta.mol2" ligand but however I'm getting a 0 length IFP returned with a message saying 
**Set centroid to 6.352 46.005 -10.864**
![Capture](https://user-images.githubusercontent.com/22572100/66031930-00686080-e522-11e9-9012-89ccb70d2bde.PNG)

How do I set the ligand centroid to the expected values?
I'm a bit new to mol2 formats.

**Comment by cbouy** [comment]
"Set centroid" is just a bad phrasing from my part. I replaced it to "Ligand centroid was detected as" in the current GitHub version, and did a few bugfixes as well. You can install the current github version with `pip install git+https://github.com/cbouy/ProLIF.git`

Here the problem is that the ligand you're using is quite special. The phenyl rings don't have other aromatic residues to interact with, and for the arsenic atom you would probably have to compute accurate charges if you want to see some electrostatic interactions. The parameters for ionic and metallic interactions might also have to be tweaked as I said previously.
![1hyv](https://user-images.githubusercontent.com/27850535/66055568-0b2cf080-e536-11e9-8b7f-aa927d078a9a.png)
